import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const src=await fs.readFile(new URL('../lib/ai/provider.js',import.meta.url),'utf8');const {testProviders}=await import('data:text/javascript;base64,'+Buffer.from(src).toString('base64'));
const cfg={provider:'nvidia',model:'primary/model',maxTokens:600,temperature:.4};process.env.AI_PROVIDER='nvidia';process.env.AI_API_KEYS='nvapi-fake-secret';process.env.GEMINI_API_KEYS='AIzaFakeBackupSecret';
let calls=[];globalThis.fetch=async(url,opts)=>{calls.push(url);if(url.includes('integrate'))return {status:401,text:async()=>JSON.stringify({error:{message:'Invalid key nvapi-fake-secret'}})};return {status:200,text:async()=>JSON.stringify({candidates:[{content:{parts:[{text:'OK'}]}}]})}};
const good=await testProviders(cfg);assert.equal(good.provider,'gemini');assert.equal(good.attempts[0].status,401);assert.equal(good.attempts[0].error,'Invalid key [redacted]');assert.equal(calls.length,2);assert.ok(!JSON.stringify(good).includes('AIzaFakeBackupSecret'));console.log('PASS provider-specific error, backup result, keys redacted');
calls=[];globalThis.fetch=async()=>{calls.push(1);return {status:200,text:async()=>JSON.stringify({choices:[{message:{content:'OK'}}]})}};assert.equal((await testProviders(cfg)).provider,'nvidia');assert.equal(calls.length,1);console.log('PASS success sends one primary request only');
process.env.AI_API_KEYS='';process.env.GEMINI_API_KEYS='';calls=[];const missing=await testProviders(cfg);assert.equal(missing.ok,false);assert.equal(calls.length,0);assert.match(missing.attempts[0].error,/No keys/);console.log('PASS absent keys -> explicit config errors, no calls');
process.env.AI_API_KEYS='fake';globalThis.fetch=async()=>{throw Object.assign(new Error('timeout'),{name:'AbortError'})};assert.match((await testProviders(cfg)).attempts[0].error,/timed out/);console.log('PASS timeout diagnostic');
process.env.AI_API_KEYS='env-unused';process.env.GEMINI_API_KEYS='';globalThis.fetch=async(url,opts)=>{assert.equal(opts.headers.authorization,'Bearer dashboard-secret');return {status:401,text:async()=>JSON.stringify({error:{message:'Rejected dashboard-secret'}})}};const dashboard=await testProviders({...cfg,primaryKeys:['dashboard-secret'],backupKeys:[]});assert.equal(dashboard.attempts[0].error,'Rejected [redacted]');console.log('PASS effective dashboard key used and redacted');
