import './local-origin.mjs';
// Isolated local fake-key test only, with AI_KEY_ENCRYPTION_SECRET on the test server.
import pg from 'pg';import assert from 'node:assert/strict';const db=new pg.Pool({connectionString:process.env.DATABASE_URL});const base=process.env.BASE||'http://localhost:3130';const key='nvapi-'+ 'FAKE'.repeat(10);const google='AIza'+ 'FAKE'.repeat(10);
async function login(path,email,password){const r=await fetch(base+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})});assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0]}
async function post(data,cookie){return fetch(base+'/api/owner/ai/keys',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify(data)})}
try{const owner=await login('/api/owner/login',process.env.OWNER_EMAIL,process.env.OWNER_PASSWORD);const admin=await login('/api/admin/login','admin@sk.test','AdminPass123');assert.equal((await post({action:'add',provider:'nvidia',value:key},admin)).status,403);assert.equal((await post({action:'add',provider:'nvidia',value:google},owner)).status,400);assert.equal((await post({action:'add',provider:'nvidia',value:key},owner)).status,200);assert.equal((await post({action:'add',provider:'nvidia',value:key},owner)).status,200);assert.equal((await post({action:'add',provider:'gemini',value:google},owner)).status,200);
const rows=(await db.query('select * from ai_provider_keys')).rows;assert.equal(rows.length,2);assert.ok(rows.every(r=>!r.encrypted_value.includes('FAKE')));const r=await fetch(base+'/api/owner/ai/keys',{headers:{cookie:owner}});const body=await r.text();assert.ok(!body.includes(key)&&!body.includes(google));assert.ok(body.includes('last4'));console.log('PASS owner-only validation, duplicate prevention, encrypted DB and masked API');
const cfg=await(await fetch(base+'/api/owner/ai',{headers:{cookie:owner}})).json();assert.equal(cfg.keys_configured,1);assert.equal(cfg.backup_keys_configured,1);console.log('PASS dashboard pool replaces 2-key env pool independently');
for(const row of rows)assert.equal((await post({action:'remove',id:row.id},owner)).status,200);
const cfg2=await(await fetch(base+'/api/owner/ai',{headers:{cookie:owner}})).json();assert.equal(cfg2.keys_configured,2);assert.equal(cfg2.backup_keys_configured,2);console.log('PASS removing last dashboard key restores env pools');
}finally{await db.query('delete from ai_provider_keys');await db.end()}
