// Install playwright separately. Run only against a local isolated test app on port 3100.
const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});const errors=[];
 const desktop=await browser.newContext({viewport:{width:1365,height:1000}});const p=await desktop.newPage();p.on('pageerror',e=>errors.push(e.message));
 const noArrows=async page=>assert.equal(await page.locator('button[aria-label="Previous photo"],button[aria-label="Next photo"]').count(),0);
 await p.goto('http://localhost:3100/shop');await noArrows(p);await p.screenshot({path:'/downloads/no-arrows-shop-desktop.png',fullPage:true});
 await p.goto('http://localhost:3100/product/street-club-tee-black');await noArrows(p);assert.match(await p.locator('body').innerText(),/R\s*450/);
 await p.screenshot({path:'/downloads/black-tee-desktop.png',fullPage:true});
 await p.locator('.gallery-track').focus();await p.keyboard.press('ArrowRight');await p.waitForTimeout(200);assert.equal(await p.locator('.gallery-count').textContent(),'2 / 3');await p.keyboard.press('End');await p.waitForTimeout(200);assert.equal(await p.locator('.gallery-count').textContent(),'3 / 3');await p.keyboard.press('Home');await p.waitForTimeout(200);
 await p.getByRole('button',{name:'View photo 2',exact:true}).click();await p.waitForTimeout(600);assert.equal(await p.locator('.gallery-count').textContent(),'2 / 3');
 await p.getByRole('button',{name:'S',exact:true}).click();await p.getByRole('button',{name:'Add to cart',exact:true}).click();await p.getByRole('status').waitFor();let cart=await p.evaluate(()=>JSON.parse(localStorage.getItem('sk-cart')));assert.equal(cart[0].slug,'street-club-tee-black');assert.equal(cart[0].price_cents,45000);assert.equal(cart[0].size,'S');assert.match(cart[0].image,/street-club-black-front/);
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const m=await mobile.newPage();m.on('pageerror',e=>errors.push(e.message));const cdp=await mobile.newCDPSession(m);
 async function swipe(locator){await locator.scrollIntoViewIfNeeded();let b=await locator.boundingBox(),x=b.x+b.width*.85,y=b.y+b.height*.5;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let j=1;j<=8;j++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-j*b.width*.085,y}]});await m.waitForTimeout(25)}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await m.waitForTimeout(600)}
 await m.goto('http://localhost:3100/shop?cat=Beanies');await noArrows(m);const card=m.locator('.card').filter({hasText:'Black stars'});await swipe(card.locator('.gallery-track'));assert.equal(await card.locator('.gallery-count').textContent(),'2 / 2');assert.match(m.url(),/\/shop/);await m.screenshot({path:'/downloads/no-arrows-shop-mobile.png',fullPage:true});
 await card.getByRole('link',{name:'View Black stars',exact:true}).last().click();await m.waitForTimeout(300);assert.match(m.url(),/\/product\/beanie-black-stars/);
 await m.goto('http://localhost:3100/product/street-club-tee-black');await noArrows(m);await m.screenshot({path:'/downloads/black-tee-mobile.png',fullPage:true});await swipe(m.locator('.gallery-track'));assert.equal(await m.locator('.gallery-count').textContent(),'2 / 3');await m.screenshot({path:'/downloads/black-tee-mobile-back.png',fullPage:true});assert.equal(await m.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await m.emulateMedia({reducedMotion:'reduce'});await m.getByRole('button',{name:'View photo 1',exact:true}).click();await m.waitForTimeout(100);assert.equal(await m.locator('.gallery-count').textContent(),'1 / 3');await m.locator('.gallery-track').focus();await m.keyboard.press('End');await m.waitForTimeout(100);assert.equal(await m.locator('.gallery-count').textContent(),'3 / 3');
 await p.goto('http://localhost:3100');await noArrows(p);await p.screenshot({path:'/downloads/no-arrows-home-desktop.png',fullPage:true});assert.equal(errors.length,0,errors.join('\n'));await browser.close();console.log('PASS no gallery arrow buttons, desktop keyboard/thumbnails, real touch swipes on cards/pages, card links, R450/S/cart front photo, reduced motion, overflow and browser errors');
})().catch(e=>{console.error(e);process.exit(1)});
