const {chromium}=require('playwright');const {Pool}=require('pg');const assert=require('node:assert/strict');const crypto=require('crypto');const http=require('http');
const db=new Pool({connectionString:process.env.DATABASE_URL});const base='http://localhost:3100';
function totp(secret){const alpha='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='';for(const c of secret)bits+=alpha.indexOf(c).toString(2).padStart(5,'0');const bytes=[];for(let i=0;i+8<=bits.length;i+=8)bytes.push(parseInt(bits.slice(i,i+8),2));const b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const h=crypto.createHmac('sha1',Buffer.from(bytes)).update(b).digest();return ((h.readUInt32BE(h[19]&15)&0x7fffffff)%1000000).toString().padStart(6,'0');}
(async()=>{await db.query("delete from rate_events;delete from login_attempts;update users set totp_enabled=false,totp_secret=null,totp_pending=null,totp_last_step=null,totp_recovery_hashes='[]' where role='owner'");const b=await chromium.launch({executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});const ctx=await b.newContext({viewport:{width:1365,height:1000}});const p=await ctx.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto(base+'/owner/login');await p.locator('input[name=email]').fill(process.env.OWNER_EMAIL);await p.locator('input[name=password]').fill(process.env.OWNER_PASSWORD);await p.getByRole('button',{name:'Log in',exact:true}).click();await p.waitForURL('**/owner/dashboard');await p.goto(base+'/owner/dashboard/security');await p.getByLabel('Current password',{exact:true}).fill(process.env.OWNER_PASSWORD);await p.getByRole('button',{name:'Set up two-step login',exact:true}).click();await p.getByAltText('Authenticator setup QR code').waitFor();const secret=(await p.locator('code').textContent()).trim();
// Synthetic local credentials only; hide QR/key in delivered visual proof.
await p.addStyleTag({content:'img[alt="Authenticator setup QR code"] { filter: blur(14px); } code { color: transparent; background: #ddd; }'});await p.screenshot({path:'/downloads/owner-mfa-setup-desktop.png',fullPage:true});await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:'/downloads/owner-mfa-setup-mobile.png',fullPage:true});await p.getByLabel('Authenticator code',{exact:true}).fill(totp(secret));await p.getByRole('button',{name:'Confirm and enable',exact:true}).click();await p.getByText('Recovery codes',{exact:true}).waitFor();await p.getByRole('button',{name:'I saved them',exact:true}).click();assert.match(await p.locator('body').innerText(),/Optional extra protection: enabled/);await p.screenshot({path:'/downloads/owner-mfa-enabled-mobile.png',fullPage:true});
// Same-site hostile form on a different port really carries the cookie.
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end('<form method="post" action="http://localhost:3100/api/owner/settings"><input name="store_announcement" value="CSRF SHOULD FAIL"></form><script>document.forms[0].submit()</script>')});await new Promise(r=>server.listen(3201,r));let rejected=false;p.on('response',r=>{if(r.url().includes('/api/owner/settings')&&r.status()===403)rejected=true});await p.goto('http://localhost:3201');await p.waitForTimeout(500);assert.ok(rejected);server.close();console.log('PASS real-browser same-site sibling-origin form rejected (403)');
// Disable with unused synthetic recovery code obtained from local database? browser codes intentionally dismissed; use new TOTP after step reset in test only.
await db.query("update users set totp_last_step=totp_last_step-1 where role='owner';delete from rate_events where key like 'mfa:%'");await p.goto(base+'/owner/dashboard/security');await p.getByLabel('Current password',{exact:true}).fill(process.env.OWNER_PASSWORD);await p.getByLabel('Authenticator code',{exact:true}).fill(totp(secret));await p.getByRole('button',{name:'Disable two-step login',exact:true}).click();await p.getByRole('button',{name:'Set up two-step login',exact:true}).waitFor();
// AI privacy staff knowledge only vs conversation grant.
const uid=(await db.query("select id from users where email='staff@sk.test'")).rows[0].id;const old=(await db.query('select permission from user_permissions where user_id=$1',[uid])).rows;await db.query("delete from user_permissions where user_id=$1 and permission like 'ai.%'",[uid]);await db.query("insert into user_permissions(user_id,permission) values($1,'ai.knowledge')",[uid]);const sc=await b.newContext({viewport:{width:1365,height:1000}});const sp=await sc.newPage();await sp.goto(base+'/admin/login');await sp.locator('input[name=email]').fill('staff@sk.test');await sp.locator('input[name=password]').fill('StaffPass123');await sp.getByRole('button',{name:'Log in',exact:true}).click();await sp.waitForURL('**/admin/dashboard');await sp.goto(base+'/admin/dashboard/ai');assert.equal(await sp.getByText('Recent conversations',{exact:true}).count(),0);await sp.screenshot({path:'/downloads/ai-knowledge-only-desktop.png',fullPage:true});await db.query("insert into user_permissions(user_id,permission) values($1,'ai.conversations')",[uid]);await sp.reload();await sp.getByText('Recent conversations',{exact:true}).waitFor();await db.query("delete from user_permissions where user_id=$1 and permission like 'ai.%'",[uid]);for(const x of old.filter(x=>x.permission.startsWith('ai.')))await db.query('insert into user_permissions(user_id,permission) values($1,$2) on conflict do nothing',[uid,x.permission]);assert.deepEqual(errors,[]);console.log('PASS MFA setup QR/key, enable/recovery UI, mobile no overflow, disable, staff titles absent until permission, no browser errors');await b.close();await db.end();})().catch(async e=>{console.error(e);await db.query("update users set totp_enabled=false,totp_secret=null,totp_pending=null,totp_last_step=null,totp_recovery_hashes='[]' where role='owner'");await db.end();process.exit(1)});
